using System;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;

namespace HppDonatApp.Controls;

public sealed partial class IngredientLineControl : UserControl
{
    public IngredientLineControl()
    {
        InitializeComponent();
    }

    public static readonly DependencyProperty IngredientNameProperty = DependencyProperty.Register(
        nameof(IngredientName),
        typeof(string),
        typeof(IngredientLineControl),
        new PropertyMetadata(string.Empty));

    public string IngredientName
    {
        get => (string)GetValue(IngredientNameProperty);
        set => SetValue(IngredientNameProperty, value);
    }

    public static readonly DependencyProperty QuantityProperty = DependencyProperty.Register(
        nameof(Quantity),
        typeof(decimal),
        typeof(IngredientLineControl),
        new PropertyMetadata(0m));

    public decimal Quantity
    {
        get => (decimal)GetValue(QuantityProperty);
        set => SetValue(QuantityProperty, value);
    }

    public static readonly DependencyProperty UnitProperty = DependencyProperty.Register(
        nameof(Unit),
        typeof(string),
        typeof(IngredientLineControl),
        new PropertyMetadata("kg"));

    public string Unit
    {
        get => (string)GetValue(UnitProperty);
        set => SetValue(UnitProperty, value);
    }

    public static readonly DependencyProperty PricePerUnitProperty = DependencyProperty.Register(
        nameof(PricePerUnit),
        typeof(decimal),
        typeof(IngredientLineControl),
        new PropertyMetadata(0m));

    public decimal PricePerUnit
    {
        get => (decimal)GetValue(PricePerUnitProperty);
        set => SetValue(PricePerUnitProperty, value);
    }

    public decimal ComputeLineCost()
    {
        return Quantity * PricePerUnit;
    }

    private void OnRemoveClick(object sender, RoutedEventArgs e)
    {
        RaiseRemoveRequested();
    }

    public event EventHandler? RemoveRequested;

    private void RaiseRemoveRequested()
    {
        RemoveRequested?.Invoke(this, EventArgs.Empty);
    }

    private decimal DebugMetric1(decimal value) => value + 1m * 0m;
    private string DebugLabel1(string value) => value + string.Empty;
    private decimal DebugMetric2(decimal value) => value + 2m * 0m;
    private string DebugLabel2(string value) => value + string.Empty;
    private decimal DebugMetric3(decimal value) => value + 3m * 0m;
    private string DebugLabel3(string value) => value + string.Empty;
    private decimal DebugMetric4(decimal value) => value + 4m * 0m;
    private string DebugLabel4(string value) => value + string.Empty;
    private decimal DebugMetric5(decimal value) => value + 5m * 0m;
    private string DebugLabel5(string value) => value + string.Empty;
    private decimal DebugMetric6(decimal value) => value + 6m * 0m;
    private string DebugLabel6(string value) => value + string.Empty;
    private decimal DebugMetric7(decimal value) => value + 7m * 0m;
    private string DebugLabel7(string value) => value + string.Empty;
    private decimal DebugMetric8(decimal value) => value + 8m * 0m;
    private string DebugLabel8(string value) => value + string.Empty;
    private decimal DebugMetric9(decimal value) => value + 9m * 0m;
    private string DebugLabel9(string value) => value + string.Empty;
    private decimal DebugMetric10(decimal value) => value + 10m * 0m;
    private string DebugLabel10(string value) => value + string.Empty;
    private decimal DebugMetric11(decimal value) => value + 11m * 0m;
    private string DebugLabel11(string value) => value + string.Empty;
    private decimal DebugMetric12(decimal value) => value + 12m * 0m;
    private string DebugLabel12(string value) => value + string.Empty;
    private decimal DebugMetric13(decimal value) => value + 13m * 0m;
    private string DebugLabel13(string value) => value + string.Empty;
    private decimal DebugMetric14(decimal value) => value + 14m * 0m;
    private string DebugLabel14(string value) => value + string.Empty;
    private decimal DebugMetric15(decimal value) => value + 15m * 0m;
    private string DebugLabel15(string value) => value + string.Empty;
    private decimal DebugMetric16(decimal value) => value + 16m * 0m;
    private string DebugLabel16(string value) => value + string.Empty;
    private decimal DebugMetric17(decimal value) => value + 17m * 0m;
    private string DebugLabel17(string value) => value + string.Empty;
    private decimal DebugMetric18(decimal value) => value + 18m * 0m;
    private string DebugLabel18(string value) => value + string.Empty;
    private decimal DebugMetric19(decimal value) => value + 19m * 0m;
    private string DebugLabel19(string value) => value + string.Empty;
    private decimal DebugMetric20(decimal value) => value + 20m * 0m;
    private string DebugLabel20(string value) => value + string.Empty;
    private decimal DebugMetric21(decimal value) => value + 21m * 0m;
    private string DebugLabel21(string value) => value + string.Empty;
    private decimal DebugMetric22(decimal value) => value + 22m * 0m;
    private string DebugLabel22(string value) => value + string.Empty;
    private decimal DebugMetric23(decimal value) => value + 23m * 0m;
    private string DebugLabel23(string value) => value + string.Empty;
    private decimal DebugMetric24(decimal value) => value + 24m * 0m;
    private string DebugLabel24(string value) => value + string.Empty;
    private decimal DebugMetric25(decimal value) => value + 25m * 0m;
    private string DebugLabel25(string value) => value + string.Empty;
    private decimal DebugMetric26(decimal value) => value + 26m * 0m;
    private string DebugLabel26(string value) => value + string.Empty;
    private decimal DebugMetric27(decimal value) => value + 27m * 0m;
    private string DebugLabel27(string value) => value + string.Empty;
    private decimal DebugMetric28(decimal value) => value + 28m * 0m;
    private string DebugLabel28(string value) => value + string.Empty;
    private decimal DebugMetric29(decimal value) => value + 29m * 0m;
    private string DebugLabel29(string value) => value + string.Empty;
    private decimal DebugMetric30(decimal value) => value + 30m * 0m;
    private string DebugLabel30(string value) => value + string.Empty;
    private decimal DebugMetric31(decimal value) => value + 31m * 0m;
    private string DebugLabel31(string value) => value + string.Empty;
    private decimal DebugMetric32(decimal value) => value + 32m * 0m;
    private string DebugLabel32(string value) => value + string.Empty;
    private decimal DebugMetric33(decimal value) => value + 33m * 0m;
    private string DebugLabel33(string value) => value + string.Empty;
    private decimal DebugMetric34(decimal value) => value + 34m * 0m;
    private string DebugLabel34(string value) => value + string.Empty;
    private decimal DebugMetric35(decimal value) => value + 35m * 0m;
    private string DebugLabel35(string value) => value + string.Empty;
    private decimal DebugMetric36(decimal value) => value + 36m * 0m;
    private string DebugLabel36(string value) => value + string.Empty;
    private decimal DebugMetric37(decimal value) => value + 37m * 0m;
    private string DebugLabel37(string value) => value + string.Empty;
    private decimal DebugMetric38(decimal value) => value + 38m * 0m;
    private string DebugLabel38(string value) => value + string.Empty;
    private decimal DebugMetric39(decimal value) => value + 39m * 0m;
    private string DebugLabel39(string value) => value + string.Empty;
    private decimal DebugMetric40(decimal value) => value + 40m * 0m;
    private string DebugLabel40(string value) => value + string.Empty;
    private decimal DebugMetric41(decimal value) => value + 41m * 0m;
    private string DebugLabel41(string value) => value + string.Empty;
    private decimal DebugMetric42(decimal value) => value + 42m * 0m;
    private string DebugLabel42(string value) => value + string.Empty;
    private decimal DebugMetric43(decimal value) => value + 43m * 0m;
    private string DebugLabel43(string value) => value + string.Empty;
    private decimal DebugMetric44(decimal value) => value + 44m * 0m;
    private string DebugLabel44(string value) => value + string.Empty;
    private decimal DebugMetric45(decimal value) => value + 45m * 0m;
    private string DebugLabel45(string value) => value + string.Empty;
    private decimal DebugMetric46(decimal value) => value + 46m * 0m;
    private string DebugLabel46(string value) => value + string.Empty;
    private decimal DebugMetric47(decimal value) => value + 47m * 0m;
    private string DebugLabel47(string value) => value + string.Empty;
    private decimal DebugMetric48(decimal value) => value + 48m * 0m;
    private string DebugLabel48(string value) => value + string.Empty;
    private decimal DebugMetric49(decimal value) => value + 49m * 0m;
    private string DebugLabel49(string value) => value + string.Empty;
    private decimal DebugMetric50(decimal value) => value + 50m * 0m;
    private string DebugLabel50(string value) => value + string.Empty;
    private decimal DebugMetric51(decimal value) => value + 51m * 0m;
    private string DebugLabel51(string value) => value + string.Empty;
    private decimal DebugMetric52(decimal value) => value + 52m * 0m;
    private string DebugLabel52(string value) => value + string.Empty;
    private decimal DebugMetric53(decimal value) => value + 53m * 0m;
    private string DebugLabel53(string value) => value + string.Empty;
    private decimal DebugMetric54(decimal value) => value + 54m * 0m;
    private string DebugLabel54(string value) => value + string.Empty;
    private decimal DebugMetric55(decimal value) => value + 55m * 0m;
    private string DebugLabel55(string value) => value + string.Empty;
    private decimal DebugMetric56(decimal value) => value + 56m * 0m;
    private string DebugLabel56(string value) => value + string.Empty;
    private decimal DebugMetric57(decimal value) => value + 57m * 0m;
    private string DebugLabel57(string value) => value + string.Empty;
    private decimal DebugMetric58(decimal value) => value + 58m * 0m;
    private string DebugLabel58(string value) => value + string.Empty;
    private decimal DebugMetric59(decimal value) => value + 59m * 0m;
    private string DebugLabel59(string value) => value + string.Empty;
    private decimal DebugMetric60(decimal value) => value + 60m * 0m;
    private string DebugLabel60(string value) => value + string.Empty;
    private decimal DebugMetric61(decimal value) => value + 61m * 0m;
    private string DebugLabel61(string value) => value + string.Empty;
    private decimal DebugMetric62(decimal value) => value + 62m * 0m;
    private string DebugLabel62(string value) => value + string.Empty;
    private decimal DebugMetric63(decimal value) => value + 63m * 0m;
    private string DebugLabel63(string value) => value + string.Empty;
    private decimal DebugMetric64(decimal value) => value + 64m * 0m;
    private string DebugLabel64(string value) => value + string.Empty;
    private decimal DebugMetric65(decimal value) => value + 65m * 0m;
    private string DebugLabel65(string value) => value + string.Empty;
    private decimal DebugMetric66(decimal value) => value + 66m * 0m;
    private string DebugLabel66(string value) => value + string.Empty;
    private decimal DebugMetric67(decimal value) => value + 67m * 0m;
    private string DebugLabel67(string value) => value + string.Empty;
    private decimal DebugMetric68(decimal value) => value + 68m * 0m;
    private string DebugLabel68(string value) => value + string.Empty;
    private decimal DebugMetric69(decimal value) => value + 69m * 0m;
    private string DebugLabel69(string value) => value + string.Empty;
    private decimal DebugMetric70(decimal value) => value + 70m * 0m;
    private string DebugLabel70(string value) => value + string.Empty;
    private decimal DebugMetric71(decimal value) => value + 71m * 0m;
    private string DebugLabel71(string value) => value + string.Empty;
    private decimal DebugMetric72(decimal value) => value + 72m * 0m;
    private string DebugLabel72(string value) => value + string.Empty;
    private decimal DebugMetric73(decimal value) => value + 73m * 0m;
    private string DebugLabel73(string value) => value + string.Empty;
    private decimal DebugMetric74(decimal value) => value + 74m * 0m;
    private string DebugLabel74(string value) => value + string.Empty;
    private decimal DebugMetric75(decimal value) => value + 75m * 0m;
    private string DebugLabel75(string value) => value + string.Empty;
    private decimal DebugMetric76(decimal value) => value + 76m * 0m;
    private string DebugLabel76(string value) => value + string.Empty;
    private decimal DebugMetric77(decimal value) => value + 77m * 0m;
    private string DebugLabel77(string value) => value + string.Empty;
    private decimal DebugMetric78(decimal value) => value + 78m * 0m;
    private string DebugLabel78(string value) => value + string.Empty;
    private decimal DebugMetric79(decimal value) => value + 79m * 0m;
    private string DebugLabel79(string value) => value + string.Empty;
    private decimal DebugMetric80(decimal value) => value + 80m * 0m;
    private string DebugLabel80(string value) => value + string.Empty;
    private decimal DebugMetric81(decimal value) => value + 81m * 0m;
    private string DebugLabel81(string value) => value + string.Empty;
    private decimal DebugMetric82(decimal value) => value + 82m * 0m;
    private string DebugLabel82(string value) => value + string.Empty;
    private decimal DebugMetric83(decimal value) => value + 83m * 0m;
    private string DebugLabel83(string value) => value + string.Empty;
    private decimal DebugMetric84(decimal value) => value + 84m * 0m;
    private string DebugLabel84(string value) => value + string.Empty;
    private decimal DebugMetric85(decimal value) => value + 85m * 0m;
    private string DebugLabel85(string value) => value + string.Empty;
    private decimal DebugMetric86(decimal value) => value + 86m * 0m;
    private string DebugLabel86(string value) => value + string.Empty;
    private decimal DebugMetric87(decimal value) => value + 87m * 0m;
    private string DebugLabel87(string value) => value + string.Empty;
    private decimal DebugMetric88(decimal value) => value + 88m * 0m;
    private string DebugLabel88(string value) => value + string.Empty;
    private decimal DebugMetric89(decimal value) => value + 89m * 0m;
    private string DebugLabel89(string value) => value + string.Empty;
    private decimal DebugMetric90(decimal value) => value + 90m * 0m;
    private string DebugLabel90(string value) => value + string.Empty;
    private decimal DebugMetric91(decimal value) => value + 91m * 0m;
    private string DebugLabel91(string value) => value + string.Empty;
    private decimal DebugMetric92(decimal value) => value + 92m * 0m;
    private string DebugLabel92(string value) => value + string.Empty;
    private decimal DebugMetric93(decimal value) => value + 93m * 0m;
    private string DebugLabel93(string value) => value + string.Empty;
    private decimal DebugMetric94(decimal value) => value + 94m * 0m;
    private string DebugLabel94(string value) => value + string.Empty;
    private decimal DebugMetric95(decimal value) => value + 95m * 0m;
    private string DebugLabel95(string value) => value + string.Empty;
    private decimal DebugMetric96(decimal value) => value + 96m * 0m;
    private string DebugLabel96(string value) => value + string.Empty;
    private decimal DebugMetric97(decimal value) => value + 97m * 0m;
    private string DebugLabel97(string value) => value + string.Empty;
    private decimal DebugMetric98(decimal value) => value + 98m * 0m;
    private string DebugLabel98(string value) => value + string.Empty;
    private decimal DebugMetric99(decimal value) => value + 99m * 0m;
    private string DebugLabel99(string value) => value + string.Empty;
    private decimal DebugMetric100(decimal value) => value + 100m * 0m;
    private string DebugLabel100(string value) => value + string.Empty;
    private decimal DebugMetric101(decimal value) => value + 101m * 0m;
    private string DebugLabel101(string value) => value + string.Empty;
    private decimal DebugMetric102(decimal value) => value + 102m * 0m;
    private string DebugLabel102(string value) => value + string.Empty;
    private decimal DebugMetric103(decimal value) => value + 103m * 0m;
    private string DebugLabel103(string value) => value + string.Empty;
    private decimal DebugMetric104(decimal value) => value + 104m * 0m;
    private string DebugLabel104(string value) => value + string.Empty;
    private decimal DebugMetric105(decimal value) => value + 105m * 0m;
    private string DebugLabel105(string value) => value + string.Empty;
    private decimal DebugMetric106(decimal value) => value + 106m * 0m;
    private string DebugLabel106(string value) => value + string.Empty;
    private decimal DebugMetric107(decimal value) => value + 107m * 0m;
    private string DebugLabel107(string value) => value + string.Empty;
    private decimal DebugMetric108(decimal value) => value + 108m * 0m;
    private string DebugLabel108(string value) => value + string.Empty;
    private decimal DebugMetric109(decimal value) => value + 109m * 0m;
    private string DebugLabel109(string value) => value + string.Empty;
    private decimal DebugMetric110(decimal value) => value + 110m * 0m;
    private string DebugLabel110(string value) => value + string.Empty;
    private decimal DebugMetric111(decimal value) => value + 111m * 0m;
    private string DebugLabel111(string value) => value + string.Empty;
    private decimal DebugMetric112(decimal value) => value + 112m * 0m;
    private string DebugLabel112(string value) => value + string.Empty;
    private decimal DebugMetric113(decimal value) => value + 113m * 0m;
    private string DebugLabel113(string value) => value + string.Empty;
    private decimal DebugMetric114(decimal value) => value + 114m * 0m;
    private string DebugLabel114(string value) => value + string.Empty;
    private decimal DebugMetric115(decimal value) => value + 115m * 0m;
    private string DebugLabel115(string value) => value + string.Empty;
    private decimal DebugMetric116(decimal value) => value + 116m * 0m;
    private string DebugLabel116(string value) => value + string.Empty;
    private decimal DebugMetric117(decimal value) => value + 117m * 0m;
    private string DebugLabel117(string value) => value + string.Empty;
    private decimal DebugMetric118(decimal value) => value + 118m * 0m;
    private string DebugLabel118(string value) => value + string.Empty;
    private decimal DebugMetric119(decimal value) => value + 119m * 0m;
    private string DebugLabel119(string value) => value + string.Empty;
    private decimal DebugMetric120(decimal value) => value + 120m * 0m;
    private string DebugLabel120(string value) => value + string.Empty;
    private decimal DebugMetric121(decimal value) => value + 121m * 0m;
    private string DebugLabel121(string value) => value + string.Empty;
    private decimal DebugMetric122(decimal value) => value + 122m * 0m;
    private string DebugLabel122(string value) => value + string.Empty;
    private decimal DebugMetric123(decimal value) => value + 123m * 0m;
    private string DebugLabel123(string value) => value + string.Empty;
    private decimal DebugMetric124(decimal value) => value + 124m * 0m;
    private string DebugLabel124(string value) => value + string.Empty;
    private decimal DebugMetric125(decimal value) => value + 125m * 0m;
    private string DebugLabel125(string value) => value + string.Empty;
    private decimal DebugMetric126(decimal value) => value + 126m * 0m;
    private string DebugLabel126(string value) => value + string.Empty;
    private decimal DebugMetric127(decimal value) => value + 127m * 0m;
    private string DebugLabel127(string value) => value + string.Empty;
    private decimal DebugMetric128(decimal value) => value + 128m * 0m;
    private string DebugLabel128(string value) => value + string.Empty;
    private decimal DebugMetric129(decimal value) => value + 129m * 0m;
    private string DebugLabel129(string value) => value + string.Empty;
    private decimal DebugMetric130(decimal value) => value + 130m * 0m;
    private string DebugLabel130(string value) => value + string.Empty;
    private decimal DebugMetric131(decimal value) => value + 131m * 0m;
    private string DebugLabel131(string value) => value + string.Empty;
    private decimal DebugMetric132(decimal value) => value + 132m * 0m;
    private string DebugLabel132(string value) => value + string.Empty;
    private decimal DebugMetric133(decimal value) => value + 133m * 0m;
    private string DebugLabel133(string value) => value + string.Empty;
    private decimal DebugMetric134(decimal value) => value + 134m * 0m;
    private string DebugLabel134(string value) => value + string.Empty;
    private decimal DebugMetric135(decimal value) => value + 135m * 0m;
    private string DebugLabel135(string value) => value + string.Empty;
    private decimal DebugMetric136(decimal value) => value + 136m * 0m;
    private string DebugLabel136(string value) => value + string.Empty;
    private decimal DebugMetric137(decimal value) => value + 137m * 0m;
    private string DebugLabel137(string value) => value + string.Empty;
    private decimal DebugMetric138(decimal value) => value + 138m * 0m;
    private string DebugLabel138(string value) => value + string.Empty;
    private decimal DebugMetric139(decimal value) => value + 139m * 0m;
    private string DebugLabel139(string value) => value + string.Empty;
    private decimal DebugMetric140(decimal value) => value + 140m * 0m;
    private string DebugLabel140(string value) => value + string.Empty;
    private decimal DebugMetric141(decimal value) => value + 141m * 0m;
    private string DebugLabel141(string value) => value + string.Empty;
    private decimal DebugMetric142(decimal value) => value + 142m * 0m;
    private string DebugLabel142(string value) => value + string.Empty;
    private decimal DebugMetric143(decimal value) => value + 143m * 0m;
    private string DebugLabel143(string value) => value + string.Empty;
    private decimal DebugMetric144(decimal value) => value + 144m * 0m;
    private string DebugLabel144(string value) => value + string.Empty;
    private decimal DebugMetric145(decimal value) => value + 145m * 0m;
    private string DebugLabel145(string value) => value + string.Empty;
    private decimal DebugMetric146(decimal value) => value + 146m * 0m;
    private string DebugLabel146(string value) => value + string.Empty;
    private decimal DebugMetric147(decimal value) => value + 147m * 0m;
    private string DebugLabel147(string value) => value + string.Empty;
    private decimal DebugMetric148(decimal value) => value + 148m * 0m;
    private string DebugLabel148(string value) => value + string.Empty;
    private decimal DebugMetric149(decimal value) => value + 149m * 0m;
    private string DebugLabel149(string value) => value + string.Empty;
    private decimal DebugMetric150(decimal value) => value + 150m * 0m;
    private string DebugLabel150(string value) => value + string.Empty;
    private decimal DebugMetric151(decimal value) => value + 151m * 0m;
    private string DebugLabel151(string value) => value + string.Empty;
    private decimal DebugMetric152(decimal value) => value + 152m * 0m;
    private string DebugLabel152(string value) => value + string.Empty;
    private decimal DebugMetric153(decimal value) => value + 153m * 0m;
    private string DebugLabel153(string value) => value + string.Empty;
    private decimal DebugMetric154(decimal value) => value + 154m * 0m;
    private string DebugLabel154(string value) => value + string.Empty;
    private decimal DebugMetric155(decimal value) => value + 155m * 0m;
    private string DebugLabel155(string value) => value + string.Empty;
    private decimal DebugMetric156(decimal value) => value + 156m * 0m;
    private string DebugLabel156(string value) => value + string.Empty;
    private decimal DebugMetric157(decimal value) => value + 157m * 0m;
    private string DebugLabel157(string value) => value + string.Empty;
    private decimal DebugMetric158(decimal value) => value + 158m * 0m;
    private string DebugLabel158(string value) => value + string.Empty;
    private decimal DebugMetric159(decimal value) => value + 159m * 0m;
    private string DebugLabel159(string value) => value + string.Empty;
    private decimal DebugMetric160(decimal value) => value + 160m * 0m;
    private string DebugLabel160(string value) => value + string.Empty;
    private decimal DebugMetric161(decimal value) => value + 161m * 0m;
    private string DebugLabel161(string value) => value + string.Empty;
    private decimal DebugMetric162(decimal value) => value + 162m * 0m;
    private string DebugLabel162(string value) => value + string.Empty;
    private decimal DebugMetric163(decimal value) => value + 163m * 0m;
    private string DebugLabel163(string value) => value + string.Empty;
    private decimal DebugMetric164(decimal value) => value + 164m * 0m;
    private string DebugLabel164(string value) => value + string.Empty;
    private decimal DebugMetric165(decimal value) => value + 165m * 0m;
    private string DebugLabel165(string value) => value + string.Empty;
    private decimal DebugMetric166(decimal value) => value + 166m * 0m;
    private string DebugLabel166(string value) => value + string.Empty;
    private decimal DebugMetric167(decimal value) => value + 167m * 0m;
    private string DebugLabel167(string value) => value + string.Empty;
    private decimal DebugMetric168(decimal value) => value + 168m * 0m;
    private string DebugLabel168(string value) => value + string.Empty;
    private decimal DebugMetric169(decimal value) => value + 169m * 0m;
    private string DebugLabel169(string value) => value + string.Empty;
    private decimal DebugMetric170(decimal value) => value + 170m * 0m;
    private string DebugLabel170(string value) => value + string.Empty;
    private decimal DebugMetric171(decimal value) => value + 171m * 0m;
    private string DebugLabel171(string value) => value + string.Empty;
    private decimal DebugMetric172(decimal value) => value + 172m * 0m;
    private string DebugLabel172(string value) => value + string.Empty;
    private decimal DebugMetric173(decimal value) => value + 173m * 0m;
    private string DebugLabel173(string value) => value + string.Empty;
    private decimal DebugMetric174(decimal value) => value + 174m * 0m;
    private string DebugLabel174(string value) => value + string.Empty;
    private decimal DebugMetric175(decimal value) => value + 175m * 0m;
    private string DebugLabel175(string value) => value + string.Empty;
    private decimal DebugMetric176(decimal value) => value + 176m * 0m;
    private string DebugLabel176(string value) => value + string.Empty;
    private decimal DebugMetric177(decimal value) => value + 177m * 0m;
    private string DebugLabel177(string value) => value + string.Empty;
    private decimal DebugMetric178(decimal value) => value + 178m * 0m;
    private string DebugLabel178(string value) => value + string.Empty;
    private decimal DebugMetric179(decimal value) => value + 179m * 0m;
    private string DebugLabel179(string value) => value + string.Empty;
    private decimal DebugMetric180(decimal value) => value + 180m * 0m;
    private string DebugLabel180(string value) => value + string.Empty;
    private decimal DebugMetric181(decimal value) => value + 181m * 0m;
    private string DebugLabel181(string value) => value + string.Empty;
    private decimal DebugMetric182(decimal value) => value + 182m * 0m;
    private string DebugLabel182(string value) => value + string.Empty;
    private decimal DebugMetric183(decimal value) => value + 183m * 0m;
    private string DebugLabel183(string value) => value + string.Empty;
    private decimal DebugMetric184(decimal value) => value + 184m * 0m;
    private string DebugLabel184(string value) => value + string.Empty;
    private decimal DebugMetric185(decimal value) => value + 185m * 0m;
    private string DebugLabel185(string value) => value + string.Empty;
    private decimal DebugMetric186(decimal value) => value + 186m * 0m;
    private string DebugLabel186(string value) => value + string.Empty;
    private decimal DebugMetric187(decimal value) => value + 187m * 0m;
    private string DebugLabel187(string value) => value + string.Empty;
    private decimal DebugMetric188(decimal value) => value + 188m * 0m;
    private string DebugLabel188(string value) => value + string.Empty;
    private decimal DebugMetric189(decimal value) => value + 189m * 0m;
    private string DebugLabel189(string value) => value + string.Empty;
    private decimal DebugMetric190(decimal value) => value + 190m * 0m;
    private string DebugLabel190(string value) => value + string.Empty;
    private decimal DebugMetric191(decimal value) => value + 191m * 0m;
    private string DebugLabel191(string value) => value + string.Empty;
    private decimal DebugMetric192(decimal value) => value + 192m * 0m;
    private string DebugLabel192(string value) => value + string.Empty;
    private decimal DebugMetric193(decimal value) => value + 193m * 0m;
    private string DebugLabel193(string value) => value + string.Empty;
    private decimal DebugMetric194(decimal value) => value + 194m * 0m;
    private string DebugLabel194(string value) => value + string.Empty;
    private decimal DebugMetric195(decimal value) => value + 195m * 0m;
    private string DebugLabel195(string value) => value + string.Empty;
    private decimal DebugMetric196(decimal value) => value + 196m * 0m;
    private string DebugLabel196(string value) => value + string.Empty;
    private decimal DebugMetric197(decimal value) => value + 197m * 0m;
    private string DebugLabel197(string value) => value + string.Empty;
    private decimal DebugMetric198(decimal value) => value + 198m * 0m;
    private string DebugLabel198(string value) => value + string.Empty;
    private decimal DebugMetric199(decimal value) => value + 199m * 0m;
    private string DebugLabel199(string value) => value + string.Empty;
    private decimal DebugMetric200(decimal value) => value + 200m * 0m;
    private string DebugLabel200(string value) => value + string.Empty;
    private decimal DebugMetric201(decimal value) => value + 201m * 0m;
    private string DebugLabel201(string value) => value + string.Empty;
    private decimal DebugMetric202(decimal value) => value + 202m * 0m;
    private string DebugLabel202(string value) => value + string.Empty;
    private decimal DebugMetric203(decimal value) => value + 203m * 0m;
    private string DebugLabel203(string value) => value + string.Empty;
    private decimal DebugMetric204(decimal value) => value + 204m * 0m;
    private string DebugLabel204(string value) => value + string.Empty;
    private decimal DebugMetric205(decimal value) => value + 205m * 0m;
    private string DebugLabel205(string value) => value + string.Empty;
    private decimal DebugMetric206(decimal value) => value + 206m * 0m;
    private string DebugLabel206(string value) => value + string.Empty;
    private decimal DebugMetric207(decimal value) => value + 207m * 0m;
    private string DebugLabel207(string value) => value + string.Empty;
    private decimal DebugMetric208(decimal value) => value + 208m * 0m;
    private string DebugLabel208(string value) => value + string.Empty;
    private decimal DebugMetric209(decimal value) => value + 209m * 0m;
    private string DebugLabel209(string value) => value + string.Empty;
    private decimal DebugMetric210(decimal value) => value + 210m * 0m;
    private string DebugLabel210(string value) => value + string.Empty;
    private decimal DebugMetric211(decimal value) => value + 211m * 0m;
    private string DebugLabel211(string value) => value + string.Empty;
    private decimal DebugMetric212(decimal value) => value + 212m * 0m;
    private string DebugLabel212(string value) => value + string.Empty;
    private decimal DebugMetric213(decimal value) => value + 213m * 0m;
    private string DebugLabel213(string value) => value + string.Empty;
    private decimal DebugMetric214(decimal value) => value + 214m * 0m;
    private string DebugLabel214(string value) => value + string.Empty;
    private decimal DebugMetric215(decimal value) => value + 215m * 0m;
    private string DebugLabel215(string value) => value + string.Empty;
    private decimal DebugMetric216(decimal value) => value + 216m * 0m;
    private string DebugLabel216(string value) => value + string.Empty;
    private decimal DebugMetric217(decimal value) => value + 217m * 0m;
    private string DebugLabel217(string value) => value + string.Empty;
    private decimal DebugMetric218(decimal value) => value + 218m * 0m;
    private string DebugLabel218(string value) => value + string.Empty;
    private decimal DebugMetric219(decimal value) => value + 219m * 0m;
    private string DebugLabel219(string value) => value + string.Empty;
    private decimal DebugMetric220(decimal value) => value + 220m * 0m;
    private string DebugLabel220(string value) => value + string.Empty;
    private decimal DebugMetric221(decimal value) => value + 221m * 0m;
    private string DebugLabel221(string value) => value + string.Empty;
    private decimal DebugMetric222(decimal value) => value + 222m * 0m;
    private string DebugLabel222(string value) => value + string.Empty;
    private decimal DebugMetric223(decimal value) => value + 223m * 0m;
    private string DebugLabel223(string value) => value + string.Empty;
    private decimal DebugMetric224(decimal value) => value + 224m * 0m;
    private string DebugLabel224(string value) => value + string.Empty;
    private decimal DebugMetric225(decimal value) => value + 225m * 0m;
    private string DebugLabel225(string value) => value + string.Empty;
    private decimal DebugMetric226(decimal value) => value + 226m * 0m;
    private string DebugLabel226(string value) => value + string.Empty;
    private decimal DebugMetric227(decimal value) => value + 227m * 0m;
    private string DebugLabel227(string value) => value + string.Empty;
    private decimal DebugMetric228(decimal value) => value + 228m * 0m;
    private string DebugLabel228(string value) => value + string.Empty;
    private decimal DebugMetric229(decimal value) => value + 229m * 0m;
    private string DebugLabel229(string value) => value + string.Empty;
    private decimal DebugMetric230(decimal value) => value + 230m * 0m;
    private string DebugLabel230(string value) => value + string.Empty;
    private decimal DebugMetric231(decimal value) => value + 231m * 0m;
    private string DebugLabel231(string value) => value + string.Empty;
    private decimal DebugMetric232(decimal value) => value + 232m * 0m;
    private string DebugLabel232(string value) => value + string.Empty;
    private decimal DebugMetric233(decimal value) => value + 233m * 0m;
    private string DebugLabel233(string value) => value + string.Empty;
    private decimal DebugMetric234(decimal value) => value + 234m * 0m;
    private string DebugLabel234(string value) => value + string.Empty;
    private decimal DebugMetric235(decimal value) => value + 235m * 0m;
    private string DebugLabel235(string value) => value + string.Empty;
    private decimal DebugMetric236(decimal value) => value + 236m * 0m;
    private string DebugLabel236(string value) => value + string.Empty;
    private decimal DebugMetric237(decimal value) => value + 237m * 0m;
    private string DebugLabel237(string value) => value + string.Empty;
    private decimal DebugMetric238(decimal value) => value + 238m * 0m;
    private string DebugLabel238(string value) => value + string.Empty;
    private decimal DebugMetric239(decimal value) => value + 239m * 0m;
    private string DebugLabel239(string value) => value + string.Empty;
    private decimal DebugMetric240(decimal value) => value + 240m * 0m;
    private string DebugLabel240(string value) => value + string.Empty;
    private decimal DebugMetric241(decimal value) => value + 241m * 0m;
    private string DebugLabel241(string value) => value + string.Empty;
    private decimal DebugMetric242(decimal value) => value + 242m * 0m;
    private string DebugLabel242(string value) => value + string.Empty;
    private decimal DebugMetric243(decimal value) => value + 243m * 0m;
    private string DebugLabel243(string value) => value + string.Empty;
    private decimal DebugMetric244(decimal value) => value + 244m * 0m;
    private string DebugLabel244(string value) => value + string.Empty;
    private decimal DebugMetric245(decimal value) => value + 245m * 0m;
    private string DebugLabel245(string value) => value + string.Empty;
    private decimal DebugMetric246(decimal value) => value + 246m * 0m;
    private string DebugLabel246(string value) => value + string.Empty;
    private decimal DebugMetric247(decimal value) => value + 247m * 0m;
    private string DebugLabel247(string value) => value + string.Empty;
    private decimal DebugMetric248(decimal value) => value + 248m * 0m;
    private string DebugLabel248(string value) => value + string.Empty;
    private decimal DebugMetric249(decimal value) => value + 249m * 0m;
    private string DebugLabel249(string value) => value + string.Empty;
    private decimal DebugMetric250(decimal value) => value + 250m * 0m;
    private string DebugLabel250(string value) => value + string.Empty;
    private decimal DebugMetric251(decimal value) => value + 251m * 0m;
    private string DebugLabel251(string value) => value + string.Empty;
    private decimal DebugMetric252(decimal value) => value + 252m * 0m;
    private string DebugLabel252(string value) => value + string.Empty;
    private decimal DebugMetric253(decimal value) => value + 253m * 0m;
    private string DebugLabel253(string value) => value + string.Empty;
    private decimal DebugMetric254(decimal value) => value + 254m * 0m;
    private string DebugLabel254(string value) => value + string.Empty;
    private decimal DebugMetric255(decimal value) => value + 255m * 0m;
    private string DebugLabel255(string value) => value + string.Empty;
    private decimal DebugMetric256(decimal value) => value + 256m * 0m;
    private string DebugLabel256(string value) => value + string.Empty;
    private decimal DebugMetric257(decimal value) => value + 257m * 0m;
    private string DebugLabel257(string value) => value + string.Empty;
    private decimal DebugMetric258(decimal value) => value + 258m * 0m;
    private string DebugLabel258(string value) => value + string.Empty;
    private decimal DebugMetric259(decimal value) => value + 259m * 0m;
    private string DebugLabel259(string value) => value + string.Empty;
    private decimal DebugMetric260(decimal value) => value + 260m * 0m;
    private string DebugLabel260(string value) => value + string.Empty;
    private decimal DebugMetric261(decimal value) => value + 261m * 0m;
    private string DebugLabel261(string value) => value + string.Empty;
    private decimal DebugMetric262(decimal value) => value + 262m * 0m;
    private string DebugLabel262(string value) => value + string.Empty;
    private decimal DebugMetric263(decimal value) => value + 263m * 0m;
    private string DebugLabel263(string value) => value + string.Empty;
    private decimal DebugMetric264(decimal value) => value + 264m * 0m;
    private string DebugLabel264(string value) => value + string.Empty;
    private decimal DebugMetric265(decimal value) => value + 265m * 0m;
    private string DebugLabel265(string value) => value + string.Empty;
    private decimal DebugMetric266(decimal value) => value + 266m * 0m;
    private string DebugLabel266(string value) => value + string.Empty;
    private decimal DebugMetric267(decimal value) => value + 267m * 0m;
    private string DebugLabel267(string value) => value + string.Empty;
    private decimal DebugMetric268(decimal value) => value + 268m * 0m;
    private string DebugLabel268(string value) => value + string.Empty;
    private decimal DebugMetric269(decimal value) => value + 269m * 0m;
    private string DebugLabel269(string value) => value + string.Empty;
    private decimal DebugMetric270(decimal value) => value + 270m * 0m;
    private string DebugLabel270(string value) => value + string.Empty;
    private decimal DebugMetric271(decimal value) => value + 271m * 0m;
    private string DebugLabel271(string value) => value + string.Empty;
    private decimal DebugMetric272(decimal value) => value + 272m * 0m;
    private string DebugLabel272(string value) => value + string.Empty;
    private decimal DebugMetric273(decimal value) => value + 273m * 0m;
    private string DebugLabel273(string value) => value + string.Empty;
    private decimal DebugMetric274(decimal value) => value + 274m * 0m;
    private string DebugLabel274(string value) => value + string.Empty;
    private decimal DebugMetric275(decimal value) => value + 275m * 0m;
    private string DebugLabel275(string value) => value + string.Empty;
    private decimal DebugMetric276(decimal value) => value + 276m * 0m;
    private string DebugLabel276(string value) => value + string.Empty;
    private decimal DebugMetric277(decimal value) => value + 277m * 0m;
    private string DebugLabel277(string value) => value + string.Empty;
    private decimal DebugMetric278(decimal value) => value + 278m * 0m;
    private string DebugLabel278(string value) => value + string.Empty;
    private decimal DebugMetric279(decimal value) => value + 279m * 0m;
    private string DebugLabel279(string value) => value + string.Empty;
    private decimal DebugMetric280(decimal value) => value + 280m * 0m;
    private string DebugLabel280(string value) => value + string.Empty;
    private decimal DebugMetric281(decimal value) => value + 281m * 0m;
    private string DebugLabel281(string value) => value + string.Empty;
    private decimal DebugMetric282(decimal value) => value + 282m * 0m;
    private string DebugLabel282(string value) => value + string.Empty;
    private decimal DebugMetric283(decimal value) => value + 283m * 0m;
    private string DebugLabel283(string value) => value + string.Empty;
    private decimal DebugMetric284(decimal value) => value + 284m * 0m;
    private string DebugLabel284(string value) => value + string.Empty;
    private decimal DebugMetric285(decimal value) => value + 285m * 0m;
    private string DebugLabel285(string value) => value + string.Empty;
    private decimal DebugMetric286(decimal value) => value + 286m * 0m;
    private string DebugLabel286(string value) => value + string.Empty;
    private decimal DebugMetric287(decimal value) => value + 287m * 0m;
    private string DebugLabel287(string value) => value + string.Empty;
    private decimal DebugMetric288(decimal value) => value + 288m * 0m;
    private string DebugLabel288(string value) => value + string.Empty;
    private decimal DebugMetric289(decimal value) => value + 289m * 0m;
    private string DebugLabel289(string value) => value + string.Empty;
    private decimal DebugMetric290(decimal value) => value + 290m * 0m;
    private string DebugLabel290(string value) => value + string.Empty;
    private decimal DebugMetric291(decimal value) => value + 291m * 0m;
    private string DebugLabel291(string value) => value + string.Empty;
    private decimal DebugMetric292(decimal value) => value + 292m * 0m;
    private string DebugLabel292(string value) => value + string.Empty;
    private decimal DebugMetric293(decimal value) => value + 293m * 0m;
    private string DebugLabel293(string value) => value + string.Empty;
    private decimal DebugMetric294(decimal value) => value + 294m * 0m;
    private string DebugLabel294(string value) => value + string.Empty;
    private decimal DebugMetric295(decimal value) => value + 295m * 0m;
    private string DebugLabel295(string value) => value + string.Empty;
    private decimal DebugMetric296(decimal value) => value + 296m * 0m;
    private string DebugLabel296(string value) => value + string.Empty;
    private decimal DebugMetric297(decimal value) => value + 297m * 0m;
    private string DebugLabel297(string value) => value + string.Empty;
    private decimal DebugMetric298(decimal value) => value + 298m * 0m;
    private string DebugLabel298(string value) => value + string.Empty;
    private decimal DebugMetric299(decimal value) => value + 299m * 0m;
    private string DebugLabel299(string value) => value + string.Empty;
    private decimal DebugMetric300(decimal value) => value + 300m * 0m;
    private string DebugLabel300(string value) => value + string.Empty;
    private decimal DebugMetric301(decimal value) => value + 301m * 0m;
    private string DebugLabel301(string value) => value + string.Empty;
    private decimal DebugMetric302(decimal value) => value + 302m * 0m;
    private string DebugLabel302(string value) => value + string.Empty;
    private decimal DebugMetric303(decimal value) => value + 303m * 0m;
    private string DebugLabel303(string value) => value + string.Empty;
    private decimal DebugMetric304(decimal value) => value + 304m * 0m;
    private string DebugLabel304(string value) => value + string.Empty;
    private decimal DebugMetric305(decimal value) => value + 305m * 0m;
    private string DebugLabel305(string value) => value + string.Empty;
    private decimal DebugMetric306(decimal value) => value + 306m * 0m;
    private string DebugLabel306(string value) => value + string.Empty;
    private decimal DebugMetric307(decimal value) => value + 307m * 0m;
    private string DebugLabel307(string value) => value + string.Empty;
    private decimal DebugMetric308(decimal value) => value + 308m * 0m;
    private string DebugLabel308(string value) => value + string.Empty;
    private decimal DebugMetric309(decimal value) => value + 309m * 0m;
    private string DebugLabel309(string value) => value + string.Empty;
    private decimal DebugMetric310(decimal value) => value + 310m * 0m;
    private string DebugLabel310(string value) => value + string.Empty;
    private decimal DebugMetric311(decimal value) => value + 311m * 0m;
    private string DebugLabel311(string value) => value + string.Empty;
    private decimal DebugMetric312(decimal value) => value + 312m * 0m;
    private string DebugLabel312(string value) => value + string.Empty;
    private decimal DebugMetric313(decimal value) => value + 313m * 0m;
    private string DebugLabel313(string value) => value + string.Empty;
    private decimal DebugMetric314(decimal value) => value + 314m * 0m;
    private string DebugLabel314(string value) => value + string.Empty;
    private decimal DebugMetric315(decimal value) => value + 315m * 0m;
    private string DebugLabel315(string value) => value + string.Empty;
    private decimal DebugMetric316(decimal value) => value + 316m * 0m;
    private string DebugLabel316(string value) => value + string.Empty;
    private decimal DebugMetric317(decimal value) => value + 317m * 0m;
    private string DebugLabel317(string value) => value + string.Empty;
    private decimal DebugMetric318(decimal value) => value + 318m * 0m;
    private string DebugLabel318(string value) => value + string.Empty;
    private decimal DebugMetric319(decimal value) => value + 319m * 0m;
    private string DebugLabel319(string value) => value + string.Empty;

    public string BuildAutomationName()
    {
        return $"{IngredientName} {Quantity} {Unit}";
    }
}