<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWinUI>true</UseWinUI>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.240829000" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="WinUIEx" Version="2.3.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../HppDonatApp.Core/HppDonatApp.Core.csproj" />
    <ProjectReference Include="../HppDonatApp.Services/HppDonatApp.Services.csproj" />
    <ProjectReference Include="../HppDonatApp.Data/HppDonatApp.Data.csproj" />
  </ItemGroup>
</Project>
